### ISSUE TITLE
Piwik dotnet Tracker not compatible with uwp/uap

### ISSUE THREAD

**Issue by DerGary** [matomo-org/piwik-dotnet-tracker#25]
Hi

I just tried to add the Piwik.Tracker NuGet Package to an UWP App but the install failed with the error: 
`Package restore failed. Rolling back package changes for 'App1'.`
So thats not really a meaningfull error message so I went and looked at the output:

```
Restoring packages for 'App1'.
Restoring packages for c:\Projects\App1\App1\project.json...
Piwik.Tracker 2.16.0 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
Piwik.Tracker 2.16.0 is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
Piwik.Tracker 2.16.0 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
Piwik.Tracker 2.16.0 is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
Piwik.Tracker 2.16.0 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
Piwik.Tracker 2.16.0 is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
Piwik.Tracker 2.16.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed for 'App1'.
Package restore failed. Rolling back package changes for 'App1'.
========== Finished ==========
```

After that I took a look at the current Piwik NuGet Package which publishes the dll in the .net40 folder. I don't really know much about the different Framework types but what i know is that to be compatible with UWP it should be in the .netcore50 or uap10.0 folder but just putting it in this folder is of course not going to work so it must also be compiled for .netcore50, so I went and tried to create a new ClassLibrary project that targets .Net for Windows Universal and copied all the code to it. I could resolve some of the dependencies but the Namespace System.Security.Cryptography which should be in the mscorlib is just not present for .Net for Windows Universal.

Maybe there is a way around this? I don't really know much about the different Frameworks and I am at my wit's end now.

Maybe you have some ideas to fix this we would like to add Piwik to our apps since we already have Piwik running.

Thank you
Gary

**Comment by julienmoumne** [comment]
As per the discussion in #29, v3.0.0 will be developed using .NET 5 to be able to provide async methods.

When v3.0.0 is released, we would be interested if you could test integrating the library in your UWP app to see if your problem is still present.

**Comment by DerGary** [comment]
No currently it's not working with version 2.16.0. This is due to it targeting .NET 4.0. UWP is compatible with .NET-Standard 1.4 or previous. If you will target 4.5 it will also not work. You should think about targeting the .NET-Standard instead of the .NET Framework this will also ensure compatibility with the .NET Framework and Xamarin which we want to use in future development to create cross platform apps.

**Comment by julienmoumne** [comment]
Thank you for testing and for this information. 

Please feel free to provide a PR if by any chance you know how to migrate to the standard you mentioned.

**Comment by huan086** [comment]
I've been able to find replacements for most of the libraries for .NET Standard 1.3. https://github.com/huan086/piwik-dotnet-tracker/tree/Standard1.3

However, I've no idea how to deal with PiwikTracker reading from HttpContext.Current. Is there a replacement in .NET Standard? Or should cookie handling be moved to a separate Piwik.Tracker.Web project that is still dependent on .NET 4.6?

**Comment by ptr1120** [comment]
Hi huan086,

this looks great. 
I also started to refactor the code for .NET Standard 1.3. ([here](https://github.com/ptr1120/piwik-dotnet-tracker/tree/IntroduceMultiPlatformSupport/Piwik.Tracker)) and stumbled over the `HttpContext` problem.
Basically there is no static `HttpContext.Current` in .Net Standard anymore, but we can get a HttpContext instance from `IHttpContextAccessor` . The bigger problem is that the `HttpContext` interface has  changed a lot. 
I am not sure whether the refactoring of these `HttpContext` methods is really worth it, therefore I think we should discuss this. I do not really understand the usage scenario of these methods using `HttpContext` , for me using the piwik-dotnet-tracker in a Web Application makes no sense. If I would have a Web Application I would not hesitate to use the piwik-javascript-tracker, since it is widely used and supported, runs on the client and is async. 
This discussion should not be misunderstood as criticism, maybe I am completely wrong in my understanding of this usage scenario since I am only experienced in using the piwik tracker in a desktop application.

One minor hint: `Uri.EscapeDataString` does not escape like expected it will e.g. fail for encoding "+” into Space [(see also](https://blogs.msdn.microsoft.com/yangxind/2006/11/08/dont-use-net-system-uri-unescapedatastring-in-url-decoding/)). Therefore I think `WebUtility.UrlDecode` will be a better replacement for `HttpUtility.UrlDecode`. 

Best regards 
Peter

**Comment by huan086** [comment]
I'm actually planning to use the tracker on a web project. The only use case is to track events. Whether the event is generated is determined by the server, thus easier for me to send it from server than from client.

URL handling in .NET is so messed up. Let me look at WebUtility.

**Comment by ptr1120** [comment]
Interesting to hear from this server side use case. Then we will have to refactor this `HttpContext` code. I thought of 2 project files.
Project 1 is the current Piwik.Tracker.csproj targeting .net 4.5 framework and one project targeting .net standard that has links to the .cs files from Piwik.Tracker.csproj. The code concerning the `HttpContext` could be extracted to a extension class and there we can either provide different implementations for both solutions or use compiler directives like I tried it here for the serializer https://github.com/ptr1120/piwik-dotnet-tracker/blob/IntroduceMultiPlatformSupport/Piwik.Tracker/SerializerExtensions.cs. 
Maybe we will need a further Test project for .net standard referencing the existing tests and testing the code for this platform.
I think aim should be one piwik tracker nuget package with 2 dlls (net45, netstandard)

**Comment by DerGary** [comment]
> Project 1 is the current Piwik.Tracker.csproj targeting .net 4.5 framework and one project targeting .net standard that has links to the .cs files from Piwik.Tracker.csproj. The code concerning the HttpContext could be extracted to a extension class and there we can either provide different implementations for both solutions or use compiler directives like I tried it here for the serializer https://github.com/ptr1120/piwik-dotnet-tracker/blob/IntroduceMultiPlatformSupport/Piwik.Tracker/SerializerExtensions.cs. Maybe we will need a further Test project for .net standard referencing the existing tests and testing the code for this platform. I think aim should be one piwik tracker nuget package with 2 dlls (net45, netstandard)

@ptr1120 Hello ptr1120, I think it would not be a good idea to have 2 Projects where one is only for .net 4.5 and one for .net standard because if you would target .net standard 1.1 for example it would also be automatically compatible with .net framework 4.5, if you would target .net standard 1.3 for example it would be compatible with .net framework 4.6. You can see which frameworks are compatible with different .net standard versions in this table: https://docs.microsoft.com/en-us/dotnet/articles/standard/library

Greetings Gary

**Comment by ptr1120** [comment]
@DerGary : thanks for your ideas. It would be very nice to provide only 1 project / library, but I am afraid, when we target netstandard we will have lot's of dependencies that are useless to users that target the monolithic .net framework. I am not really experienced up to now with providing multi platform supporting libraries and there have been many changes concerning this in the last time. I tried to orientate myself at other nuget packages providing multi platform support like in [Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json).

**Comment by DerGary** [comment]
@ptr1120 I didn't thought of that, that is a valid point. I'm also not really familiar with multi platform support, I just thought it would be easier and more maintainable just having one project/code base.

**Comment by chrisgl** [comment]
I have the problem now, too.
I want to use this Library in a Project with .Net Core 2.0 or lower.
There I want to track my WebAPI.
So having this library as a .Net Standard 2.0 or lower Library would be really nice.

**Comment by uncled1023** [comment]
Same.  Looking at upgrading my site to asp.net core 2, but the lack of a tracking/analytics API in .net Core is preventing the conversion.

**Comment by coderb** [comment]
https://github.com/matomo-org/piwik-dotnet-tracker/pull/69
I've submitted a pull request for .net standard support.
