### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by fahadabdulaziz** [matomo-org/piwik-dotnet-tracker#74]
Hi, 
Is this repo dead? as I see it's been three years since last update.

Thanks

**Comment by mattab** [comment]
Hello, thanks for creating the issue. The report is not dead, but it is not actively maintained anymore, and we would like to invite a new maintainer or two to join. So if anyone wants to become a new maintainer, please let me know!

**Comment by fahadabdulaziz** [comment]
Thanks, 
I could help maintain this repo & dotnet-api repo ..

**Comment by fahadabdulaziz** [comment]
@mattab 
Suggestion to update this repo:
- Rename the repo and packages to the Matomo.
- Change packages to .net standard so it be used by .net framework & core users.
- Update tests to use xUnit and .net core 
- Then catchup with the API to up-to-date with the main project.

Regards

**Comment by mattab** [comment]
Hi @fahadabdulaziz 
this sounds good to me. 

Would you maybe be able to help on this and open pull requests? 
it would be great to keep BC if possible and if not, quickly document how people can upgrade to the new version.
(btw I can rename the projects, let me know when it's ready to be renamed later)

Thanks,

**Comment by fahadabdulaziz** [comment]
Great, 
I'll start on the most important thing converting the project to .NET Standard to be used by most .NET platform users. then work on the rest.

**Comment by fahadabdulaziz** [comment]
I created pull request https://github.com/matomo-org/piwik-dotnet-tracker/pull/75
